#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/zc963/nrn/nrn/neuron_install/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/zc963/nrn/nrn/neuron_install/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/zc963/Research/Motor Cortex Model/Stylized-Cell-Inference/cell_inference/resources/compiled/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
