#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/matt/venvs/sbi/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/matt/venvs/sbi/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/matt/repos/Research/neurolab_file_transfer/compiled/x86_64/.libs/libnrnmech.so" "$@"
